### PR TITLE
Parse relative months and years

### LINKED ISSUE #1696: Relative time ambiguity across DST adjustments
### Current behavior 😯

When [`gix-date::date time::parse::relative::various`](https://github.com/GitoxideLabs/gitoxide/blob/197d31aff5a602c3107c32661340e89781ad0b33/gix-date/tests/time/parse.rs#L179-L201) is run in an environment that uses local time in a time zone that has daylight savings clock adjustments, it fails in the two weeks after daylight saving time changes. All other `gix-date` tests pass.

For example, my time zone is [Eastern Time](https://en.wikipedia.org/wiki/Eastern_Time_Zone), which had a DST clock adjustment from EDT (UTC-4) to EST (UTC-5) on 3 November 2024. Since then, and until two weeks later, the test failed when I ran it locally. Here's a run from 9 November 2024:
 
```text
        FAIL [   0.310s] gix-date::date time::parse::relative::various

--- STDOUT:              gix-date::date time::parse::relative::various ---

running 1 test
test time::parse::relative::various ... FAILED

failures:

failures:
    time::parse::relative::various

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 27 filtered out; finished in 0.31s


--- STDERR:              gix-date::date time::parse::relative::various ---
thread 'time::parse::relative::various' panicked at gix-date/tests/time/parse.rs:195:9:
assertion `left == right` failed: relative times differ
  left: 2024-10-26T20:22:51Z
 right: 2024-10-26T19:22:51Z
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------
     Summary [   0.325s] 29 tests run: 28 passed, 1 failed, 0 skipped
        FAIL [   0.310s] gix-date::date time::parse::relative::various
error: test run failed
```

Under those conditions, the time is off by one hour, due to ambiguity of phrases like `2 weeks ago`. If there was a recent daylight savings adjustment to local time, then was `2 weeks` ago the current time minus the [usual](https://www.wolframalpha.com/input?i=2+weeks+in+hours) 336 hours? Or was `2 weeks ago` the time, fourteen calendar days prior, at which local clocks showed the time that local clocks show now? Often these two interpretations of relative times coincide, but they do not always.

The test failed on GNU/Linux, macOS, and Windows, and at least on GNU/Linux and macOS, it went away when `TZ=UTC` is set. With no change to the code, the test started passing again, on all systems, on 17 November 2024, but the bug is still present.

This bug has not been detected automatically on CI, because the environment on GitHub Actions runners uses UTC rather than local time.

(This is the bug that the mention of `TZ=UTC` in d74e919 (#1652) alludes to.)

### Expected behavior 🤔

I am uncertain whether it is the code under test, or the test itself, that should be changed. But if we want to interpret relative times like "2 weeks ago" in the same way GNU/Linux `date -d` does, and in the way I *think* Git does (see below for details), then the code under test would have to be changed.

Either way, the bug is not specific to 2-week intervals. if the code is wrong, then the test's use of `2 weeks ago` is merely a limitation in when the test is able to identify the code as wrong. If the test is wrong, then while the failure only occurs under limited conditions, the interpretation of relative time that it expresses is still broader.

This is to say that even if it is (only) the test that should change, I think making the interval shorter so that it fails less often would not be the right way to go about it.

Also, either way, we should probably make the test check multiple relative time strings representing intervals of widely varying length.

### Git behavior

I don't know if I'm looking at the most relevant Git behavior, but the easiest to examine are the tests in [`t0006-date.sh`](https://github.com/git/git/blob/master/t/t0006-date.sh). If I understand correctly, relative date strings [represent](https://github.com/git/git/blob/04eaff62f286226f501dd21f069e0e257aee11a6/t/t0006-date.sh#L16-L35) exact numbers of seconds elapsed:

```sh
check_relative() {
	t=$(($GIT_TEST_DATE_NOW - $1))
	echo "$t -> $2" >expect
	test_expect_${3:-success} "relative date ($2)" "
	test-tool date relative $t >actual &&
	test_cmp expect actual
	"
}

check_relative 5 '5 seconds ago'
check_relative 300 '5 minutes ago'
check_relative 18000 '5 hours ago'
check_relative 432000 '5 days ago'
check_relative 1728000 '3 weeks ago'
check_relative 13000000 '5 months ago'
check_relative 37500000 '1 year, 2 months ago'
check_relative 55188000 '1 year, 9 months ago'
check_relative 630000000 '20 years ago'
check_relative 31449600 '12 months ago'
check_relative 62985600 '2 years ago'
```

[Those tests pass](https://gist.github.com/EliahKagan/60726d8600135b3876258d61bb49fe7c) when run today, on an Arch Linux system set to `America/New York` and using local time, including when the script is run directly. If `git` behaved analogously to the current behavior of `gix-date`, then I would expect the `3 weeks ago` and `5 months ago` cases, as well as some others, to have failed. I ran that test script at the tip of the `master` branch, with:

```sh
make -j10
cd t
./t0006-date.sh
```

So that would agree with what `gix-date`'s test suite is asserting, while disagreeing with the current `gix-date` behavior. It seems to me that this may be a reason to consider our existing test in `gix-date` correct, and the current behavior of the `gix-date` being tested as incorrect.

### Steps to reproduce 🕹

Although the tests don't fail in my time zone anymore, because 2 weeks ago is now after the DST adjustment, there are a few approaches that may reproduce it.

One is to use a tool like [`faketime`](https://manpages.debian.org/stable/faketime/faketime.1.en.html). This carries some subtleties, though, since accesses to date and time information are not always guaranteed to go through the functions it patches, and since cursory experimentation with `faketime` and the `date` command suggests that locale-sensitive interpretation of strings like `EST` and `EDT` as time zone offsets does not always behave the way it did at the date and time `faketime` attempts to fake it to.

Another is to set the clock back. This will carry fewer subtleties but may be undesirable.

Instead, assuming one's time zone has DST adjustments, I suggest reproducing this by modifying the interval in the test from `2 weeks ago` to an interval that refers to a date where local time used a different UTC offset than currently.

`5 months ago` would be nearly ideal, but cannot be used because [we don't yet](https://github.com/GitoxideLabs/gitoxide/blob/197d31aff5a602c3107c32661340e89781ad0b33/gix-date/src/parse.rs#L156) parse months or years, so that would give `InvalidDateString { input: "5 months ago" }`. (The absence of parsing of months or years might be considered a bug, but it is not this bug.)

A sufficient number of weeks will work, though. For example, starting in the top-level `gitoxide` directory, the interval can be changed from 2 to 20 weeks, which is approximately 5 months and should produce the bug at most (though not all) times of the year in most time zones where DST adjustments are made:

```sh
cd gix-date
sed -i.orig 's/two_weeks_ago/twenty_weeks_ago/; s/2\.weeks/20.weeks/; s/2 weeks ago/20 weeks ago/' tests/time/parse.rs
git --no-pager diff
cargo nextest run time::parse::relative::various
```

*Edit:* If #1697 is merged then the procedure here with `sed -i` will no longer be correct or needed, and the bug will automatically be observable at any time of year if it could be observed before at some time of year.

Running those commands on the test system produces the bug as intended:

```text
ek in 🌐 catenary in gitoxide on  main is 📦 v0.38.0 via 🦀 v1.82.0
❯ cd gix-date

ek in 🌐 catenary in gitoxide/gix-date on  main is 📦 v0.9.1 via 🦀 v1.82.0
❯ sed -i.orig 's/two_weeks_ago/twenty_weeks_ago/; s/2\.weeks/20.weeks/; s/2 weeks ago/20 weeks ago/' tests/time/parse.rs

ek in 🌐 catenary in gitoxide/gix-date on  main [!?] is 📦 v0.9.1 via 🦀 v1.82.0
❯ git --no-pager diff
diff --git a/gix-date/tests/time/parse.rs b/gix-date/tests/time/parse.rs
index 545fbb7fc..8b0475c1d 100644
--- a/gix-date/tests/time/parse.rs
+++ b/gix-date/tests/time/parse.rs
@@ -179,9 +179,9 @@ mod relative {
     #[test]
     fn various() {
         let now = SystemTime::now();
-        let two_weeks_ago = gix_date::parse("2 weeks ago", Some(now)).unwrap();
-        assert_eq!(Sign::Plus, two_weeks_ago.sign);
-        assert_eq!(0, two_weeks_ago.offset);
+        let twenty_weeks_ago = gix_date::parse("20 weeks ago", Some(now)).unwrap();
+        assert_eq!(Sign::Plus, twenty_weeks_ago.sign);
+        assert_eq!(0, twenty_weeks_ago.offset);
         let expected = Zoned::try_from(now)
             .unwrap()
             // account for the loss of precision when creating `Time` with seconds
@@ -191,9 +191,9 @@ mod relative {
                     .mode(jiff::RoundMode::Trunc),
             )
             .unwrap()
-            .saturating_sub(2.weeks());
+            .saturating_sub(20.weeks());
         assert_eq!(
-            jiff::Timestamp::from_second(two_weeks_ago.seconds).unwrap(),
+            jiff::Timestamp::from_second(twenty_weeks_ago.seconds).unwrap(),
             expected.timestamp(),
             "relative times differ"
         );

ek in 🌐 catenary in gitoxide/gix-date on  main [!?] is 📦 v0.9.1 via 🦀 v1.82.0
❯ cargo nextest run time::parse::relative::various
   Compiling gix-date v0.9.1 (/home/ek/repos/gitoxide/gix-date)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.92s
------------
 Nextest run ID 55a072b6-40a8-4bd9-b177-58e4158ce1fe with nextest profile: default
    Starting 1 test across 2 binaries (28 tests skipped)
        FAIL [   0.014s] gix-date::date time::parse::relative::various

--- STDOUT:              gix-date::date time::parse::relative::various ---

running 1 test
test time::parse::relative::various ... FAILED

failures:

failures:
    time::parse::relative::various

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 27 filtered out; finished in 0.01s


--- STDERR:              gix-date::date time::parse::relative::various ---
thread 'time::parse::relative::various' panicked at gix-date/tests/time/parse.rs:195:9:
assertion `left == right` failed: relative times differ
  left: 2024-07-05T18:55:17Z
 right: 2024-07-05T17:55:17Z
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure
------------
     Summary [   0.015s] 1 test run: 0 passed, 1 failed, 28 skipped
        FAIL [   0.014s] gix-date::date time::parse::relative::various
error: test run failed
```

Although less reproducible, it may be more intuitive to use a shorter interval. At the moment, 3 weeks is sufficient. A run changing 2 weeks to 3 (rather than 20) weeks [can be seen  here](https://gist.github.com/EliahKagan/881312c239e4a8fbdaa7412645a0cd12).

### PR DESCRIPTION
**Pull request by EliahKagan**
*Update: This now also fixes #1696. See 856b385 and https://github.com/GitoxideLabs/gitoxide/pull/1702#pullrequestreview-2457392772.*

This extends `gix_date::parse::relative::span` to recognize times with "months" and "years", as in "3 months ago" and "2 years ago".

The actual change here is very simple, because it is directly facilitated by #1474.

The units "seconds", "minutes", "hours", "days", and "weeks" continue to be recognized (as before). Relative times like "1 year, 2 months ago" remain unrecognized.

For background, see 43b6c06 (#498), c5c6bf6, https://github.com/GitoxideLabs/gitoxide/pull/1474#discussion_r1694769988, and https://github.com/GitoxideLabs/gitoxide/issues/1696#issuecomment-2495526654.

Note that this change does not fix issue #1696, which continues to apply to the interpretation of "days" and "weeks", and now also applies in the same way to the interpretation of "months" and "years". (It continues not to apply to the interpretation of "seconds", "minutes", and "hours".)

The tests are updated to cover "months" and "years", as well as to exercise a wider range of relative times, including showing which units (e.g. "days") are affected by #1696. A few sub-cases, of those adjusted or added here, test strings from a related test in Git, to allow comparison. But most are not related to cases there.

As before, the tests pass on CI, or when the time zone is otherwise UTC, or with local time zones that never have DST adjustments.

The sub-cases are reordered to be monotone increasing in the magnitude of the relative intervals tested (and thus monotone decreasing in the associated absolute timestamps), and the original input is kept zipped into the `actual` and `expected` arrays being compared. This way, if the assertion fails (such as due to #1696), it is clear and readable which sub-cases failed and exactly how, as well as what all the sub-cases are and what each sub-case tests.

Reordering the sub-cases and preserving the inputs they parse in this way avoids the disadvantages of #1697 while keeping, and expanding on, its benefits.

Failure, where it occurs, now looks like:

    --- STDERR:              gix-date::date time::parse::relative::various ---
    thread 'time::parse::relative::various' panicked at gix-date\tests\time\parse.rs:252:9:
    assertion failed: `(left == right)`: relative times differ

    Diff < left / right > :
     [
         (
             "5 seconds ago",
             2024-11-24T23:51:49Z,
         ),
         (
             "5 minutes ago",
             2024-11-24T23:46:54Z,
         ),
         (
             "5 hours ago",
             2024-11-24T18:51:54Z,
         ),
         (
             "5 days ago",
             2024-11-19T23:51:54Z,
         ),
         (
             "3 weeks ago",
             2024-11-03T23:51:54Z,
         ),
         (
             "21 days ago",
             2024-11-03T23:51:54Z,
         ),
         (
             "504 hours ago",
             2024-11-03T23:51:54Z,
         ),
         (
             "30240 minutes ago",
             2024-11-03T23:51:54Z,
         ),
         (
             "2 months ago",
    <        2024-09-24T23:51:54Z,
    >        2024-09-24T22:51:54Z,
         ),
         (
             "1460 hours ago",
             2024-09-25T03:51:54Z,
         ),
         (
             "87600 minutes ago",
             2024-09-25T03:51:54Z,
         ),
         (
             "14 weeks ago",
    <        2024-08-18T23:51:54Z,
    >        2024-08-18T22:51:54Z,
         ),
         (
             "98 days ago",
    <        2024-08-18T23:51:54Z,
    >        2024-08-18T22:51:54Z,
         ),
         (
             "2352 hours ago",
             2024-08-18T23:51:54Z,
         ),
         (
             "141120 minutes ago",
             2024-08-18T23:51:54Z,
         ),
         (
             "5 months ago",
    <        2024-06-24T23:51:54Z,
    >        2024-06-24T22:51:54Z,
         ),
         (
             "3650 hours ago",
             2024-06-25T21:51:54Z,
         ),
         (
             "219000 minutes ago",
             2024-06-25T21:51:54Z,
         ),
         (
             "26 weeks ago",
    <        2024-05-26T23:51:54Z,
    >        2024-05-26T22:51:54Z,
         ),
         (
             "182 days ago",
    <        2024-05-26T23:51:54Z,
    >        2024-05-26T22:51:54Z,
         ),
         (
             "4368 hours ago",
             2024-05-26T23:51:54Z,
         ),
         (
             "262080 minutes ago",
             2024-05-26T23:51:54Z,
         ),
         (
             "8 months ago",
    <        2024-03-24T23:51:54Z,
    >        2024-03-24T22:51:54Z,
         ),
         (
             "5840 hours ago",
             2024-03-26T15:51:54Z,
         ),
         (
             "350400 minutes ago",
             2024-03-26T15:51:54Z,
         ),
         (
             "38 weeks ago",
             2024-03-03T23:51:54Z,
         ),
         (
             "266 days ago",
             2024-03-03T23:51:54Z,
         ),
         (
             "6384 hours ago",
             2024-03-03T23:51:54Z,
         ),
         (
             "383040 minutes ago",
             2024-03-03T23:51:54Z,
         ),
         (
             "11 months ago",
             2023-12-24T23:51:54Z,
         ),
         (
             "8030 hours ago",
             2023-12-26T09:51:54Z,
         ),
         (
             "481800 minutes ago",
             2023-12-26T09:51:54Z,
         ),
         (
             "14 months ago",
    <        2023-09-24T23:51:54Z,
    >        2023-09-24T22:51:54Z,
         ),
         (
             "21 months ago",
             2023-02-24T23:51:54Z,
         ),
         (
             "2 years ago",
             2022-11-24T23:51:54Z,
         ),
         (
             "20 years ago",
             2004-11-24T23:51:54Z,
         ),
         (
             "630720000 seconds ago",
             2004-11-29T23:51:54Z,
         ),
     ]

---

I've posted https://github.com/GitoxideLabs/gitoxide/issues/1696#issuecomment-2496472747 about why I think the changes here may be okay to do even before the main in https://github.com/GitoxideLabs/gitoxide/issues/1696#issuecomment-2495526654 (that would actually fix issue #1696) is not yet done.

It may be that this is an excessive number of lines of test output to show in a commit message (3082d40). I've included it, as I have done in previous changes to that test, since it will not be seen on CI or even in all local time zones, and since it makes much clearer how and why the test's output format has changed.

Ordinarily, I would not be reluctant to make a commit message that long. But in this case, it's a conventional commit with `feat:`, so I expect it to make its way into the changelog. The test is probably of less interest to future readers of the changelog and in any case is not, really, technically even part of the feature. I could put the test in its own commit, as I often do with tests. But the description of what the output looks like would be inaccurate if that commit precedes the commit that adds support for months and years--it produces a parsing error until support is added, whereas the test output that is informative is the output showing that we still, and better, see what is going on with #1696.

Anyway, I don't know if that is really to be considered a problem, but I mention it so that it will be noticed if it is.

### CODE REVIEW

File: gix-date/src/parse.rs [hunk 1]
```diff
@@ -153,7 +153,8 @@ mod relative {
             "hour" => Span::new().try_hours(units),
             "day" => Span::new().try_days(units),
             "week" => Span::new().try_weeks(units),
-            // TODO months & years? YES
+            "month" => Span::new().try_months(units),
+            "year" => Span::new().try_years(units),
             // Ignore values you don't know, assume seconds then (so does git)
```
Comment (EliahKagan) [inline gix-date/src/parse.rs:158]: Although it's not specific to the changes here, it occurs to me that I'm not confident I understand this comment. I don't think it's describing the behavior of this function, which does not automatically cause text like "7 blahs" to be interpreted as "7 seconds". Maybe this comment should be somewhere else? Or, is it really an accurate description even of how this function is currently used?

**Comment by EliahKagan** [comment]
From the refactoring in d140ad4:

> - place expectations to the right, actuals on the left.

Good idea. I had kept the way it was before, but on reflection this was not likely (or not likely still) intended, since not all assertions in the function had been using the same convention.

> - fix test expectation and make clear that relative dates are all UTC.

Does this actually do the rest of https://github.com/GitoxideLabs/gitoxide/issues/1696#issuecomment-2495526654, i.e. fix issue #1696? (Normally I might read the code carefully and try it out, rather than asking immediately, but I wanted to ask this before the PR is merged, in case the commit is not just a refactoring and should be differently titled.)

**Review by Byron — APPROVED** [review]
Thanks a lot for your help with this!

When looking at the exhaustive tests, I can't shake the feeling that other parts of `gix-date` are completely under-tested. And from my memory I can tell that I never put a lot of emphasis on this crate, just wanted to have 'something' so dates are just usable enough.

In any case, I definitely count this is a step in the right direction, with the current implementation probably covering the most common cases at last.

Regarding the commit message, I think tools should enable developers, and I hope that the message comes out OK in the changelog without preventing publishing. But when it does, I will just have to fix it and that's OK.

Please note that I underhandedly fixed the 'UTC-issue', which truly was just an incorrect test expectation - the implementation is already faithful to Git, it was just the test who wasn't faithful to it.

Also, I put the actual value on the left of an assertion, and added a third argument to further explain what's going on when I thought it could make a difference.

**Comment by Byron** [comment]
> Does this actually do the rest of [#1696 (comment)](https://github.com/GitoxideLabs/gitoxide/issues/1696#issuecomment-2495526654), i.e. fix issue #1696? (Normally I might read the code carefully and try it out, rather than asking immediately, but I wanted to ask this before the PR is merged, in case the commit is not just a refactoring and should be differently titled.)

Probably I shouldn't have 'fixed' this underhandedly, so I disabled the auto-merge and invite you to split the commit. To me it was just a minor thing in the end, as I did have local test failures which I think were well enough understood to fix them. All seems alright, as I think it was just an incorrect test expectation that caused trouble.

**Comment by EliahKagan** [comment]
I've gone ahead and split the commit. For 856b385, I mentioned in the commit message that it fixes #1696, but didn't make it a conventional commit since it only changes the test.

I've also tested this locally on Windows 10 (x64) and Arch Linux (x64), with local time such that the tests had previous failed, and with `TZ=UTC` (which had previously passed). All `gix-date` tests now pass in all four combinations.

**Comment by EliahKagan** [comment]
I've caused the failing `test-32-bit` job to re-run, and it passed. Also, it had failed before any gitoxide code or tests had run, or even compiled. So it is quite unlikely to be related to any changes here. Assuming the messages in the split commits are okay, I think this is ready to go.

**Comment by Byron** [comment]
Awesome, thank you!
